apiVersion: v1
data:
  config.json: |
    {
      "credHelpers": {
        "<aws-account-id>.dkr.ecr.eu-central-1.amazonaws.com": "ecr-login"
      }
    }
kind: ConfigMap
metadata:
  name: docker-config
  namespace: jenkins
